//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soundcloud_Playlist_Downloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soundcloud_Playlist_Downloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language=한국어 (Korean)
        ///Author=HongSic (HSKernel)
        ///
        /////API Config 영역
        ///STR_APICONFIG_TITLE=API 설정
        ///STR_APICONFIG_DESC=이 설정은 클라이언트 ID를 변경합니다.\n만약 API가 인증을 거부한다고 뜨면 클라이언트 ID가 더 이상 작동하지 않는 것입니다.\n버튼 밑의 링크를 눌러 새 ID를 만드세요.\nhttp://soundcloud.com/you/apps/new
        ///STR_APICONFIG_ACTIVE=활성화
        ///STR_APICONFIG_CLIENTID=클라이언트 ID
        ///STR_APICONFIG_CUSTOMID=사용자 ID
        ///STR_APICONFIG_SAVE=설정 저장
        ///STR_APICONFIG_LINK=클릭하여 새 ID 만들기.
        /// </summary>
        internal static string Language_Korean {
            get {
                return ResourceManager.GetString("Language_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;kind&quot;:&quot;track&quot;,&quot;id&quot;:166300320,&quot;created_at&quot;:&quot;2014/09/05 03:05:46 +0000&quot;,&quot;user_id&quot;:1377057,&quot;duration&quot;:61027,&quot;commentable&quot;:true,&quot;state&quot;:&quot;finished&quot;,&quot;original_content_size&quot;:1467998,&quot;last_modified&quot;:&quot;2018/10/30 12:06:55 +0000&quot;,&quot;sharing&quot;:&quot;public&quot;,&quot;tag_list&quot;:&quot;\&quot;Maroon 5\&quot; \&quot;Adam Levine\&quot;&quot;,&quot;permalink&quot;:&quot;maroon-5-sugar&quot;,&quot;streamable&quot;:false,&quot;embeddable_by&quot;:&quot;all&quot;,&quot;purchase_url&quot;:&quot;http://smarturl.it/M5V?IQid=sc&quot;,&quot;purchase_title&quot;:&quot;Buy this Song&quot;,&quot;label_id&quot;:null,&quot;genre&quot;:&quot;Pop&quot;,&quot;title&quot;:&quot;Maroon 5 - Sugar&quot;,&quot;description&quot;:&quot;Buy on  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleTrack1 {
            get {
                return ResourceManager.GetString("SampleTrack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;kind&quot;:&quot;track&quot;,&quot;id&quot;:524711901,&quot;created_at&quot;:&quot;2018/11/04 18:28:16 +0000&quot;,&quot;user_id&quot;:20172471,&quot;duration&quot;:191208,&quot;commentable&quot;:true,&quot;state&quot;:&quot;finished&quot;,&quot;original_content_size&quot;:7645518,&quot;last_modified&quot;:&quot;2018/11/09 03:38:31 +0000&quot;,&quot;sharing&quot;:&quot;public&quot;,&quot;tag_list&quot;:&quot;\&quot;KDA \&quot; K/DA POPSTARS Leagueoflegends Kpop&quot;,&quot;permalink&quot;:&quot;kda-popstars-ft-madison-beer-gi-dle-jaira-burns&quot;,&quot;streamable&quot;:true,&quot;embeddable_by&quot;:&quot;all&quot;,&quot;purchase_url&quot;:null,&quot;purchase_title&quot;:null,&quot;label_id&quot;:null,&quot;genre&quot;:&quot;Pop&quot;,&quot;title&quot;:&quot;K/DA - POP/STARS (ft Madison B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleTrack2 {
            get {
                return ResourceManager.GetString("SampleTrack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon scdownloader {
            get {
                object obj = ResourceManager.GetObject("scdownloader", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
