//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soundcloud_Playlist_Downloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soundcloud_Playlist_Downloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Language: 한국어 (Korean)
        /////Author: HongSic (HSKernel)
        ///
        /////공통영역
        ///LANGUAGE=한국어
        ///STR_ERR=오류
        ///STR_ABORT=중단
        ///STR_SYNCHRONIZE=동기화
        ///
        /////메인창 영역
        ///STR_MAIN_TITLE_STABLE=사운드 클라우드 재생목록 동기화 {0} 안정화 버전
        ///STR_MAIN_MENU_CONFIGS=구성 설정
        ///STR_MAIN_MENU_CONFIG=구성 설정
        ///STR_MAIN_MENU_CLIENT=API 설정
        ///STR_MAIN_MENU_UPDATE=업데이트(판올림)
        ///STR_MAIN_MENU_ABOUT=이 프로그램은
        ///STR_MAIN_MENU_LNG=언어
        ///
        ///STR_MAIN_BASIC=기본 설정
        ///STR_MAIN_BASIC_URL=사운드 클라우드 URL (주소)
        ///STR_MAIN_BASIC_DIR=로컬 디렉터리
        ///STR_MAIN_BASIC_BROWSE=찾아보기
        ///STR_MAIN_BASIC_DM=다운로드 방법
        ///STR_MAI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Language_Korean {
            get {
                return ResourceManager.GetString("Language_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;kind&quot;:&quot;track&quot;,&quot;id&quot;:166300320,&quot;created_at&quot;:&quot;2014/09/05 03:05:46 +0000&quot;,&quot;user_id&quot;:1377057,&quot;duration&quot;:61027,&quot;commentable&quot;:true,&quot;state&quot;:&quot;finished&quot;,&quot;original_content_size&quot;:1467998,&quot;last_modified&quot;:&quot;2018/10/30 12:06:55 +0000&quot;,&quot;sharing&quot;:&quot;public&quot;,&quot;tag_list&quot;:&quot;\&quot;Maroon 5\&quot; \&quot;Adam Levine\&quot;&quot;,&quot;permalink&quot;:&quot;maroon-5-sugar&quot;,&quot;streamable&quot;:false,&quot;embeddable_by&quot;:&quot;all&quot;,&quot;purchase_url&quot;:&quot;http://smarturl.it/M5V?IQid=sc&quot;,&quot;purchase_title&quot;:&quot;Buy this Song&quot;,&quot;label_id&quot;:null,&quot;genre&quot;:&quot;Pop&quot;,&quot;title&quot;:&quot;Maroon 5 - Sugar&quot;,&quot;description&quot;:&quot;Buy on  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleTrack1 {
            get {
                return ResourceManager.GetString("SampleTrack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;kind&quot;:&quot;track&quot;,&quot;id&quot;:524711901,&quot;created_at&quot;:&quot;2018/11/04 18:28:16 +0000&quot;,&quot;user_id&quot;:20172471,&quot;duration&quot;:191208,&quot;commentable&quot;:true,&quot;state&quot;:&quot;finished&quot;,&quot;original_content_size&quot;:7645518,&quot;last_modified&quot;:&quot;2018/11/09 03:38:31 +0000&quot;,&quot;sharing&quot;:&quot;public&quot;,&quot;tag_list&quot;:&quot;\&quot;KDA \&quot; K/DA POPSTARS Leagueoflegends Kpop&quot;,&quot;permalink&quot;:&quot;kda-popstars-ft-madison-beer-gi-dle-jaira-burns&quot;,&quot;streamable&quot;:true,&quot;embeddable_by&quot;:&quot;all&quot;,&quot;purchase_url&quot;:null,&quot;purchase_title&quot;:null,&quot;label_id&quot;:null,&quot;genre&quot;:&quot;Pop&quot;,&quot;title&quot;:&quot;K/DA - POP/STARS (ft Madison B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleTrack2 {
            get {
                return ResourceManager.GetString("SampleTrack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon scdownloader {
            get {
                object obj = ResourceManager.GetObject("scdownloader", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
