using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using Soundcloud_Playlist_Downloader.JsonObjects;

namespace Soundcloud_Playlist_Downloader.Utils
{
    internal class PlaylistUtils
    {
        private const string GeneratedBy = "Generated by the SoundCloud Playlist Sync tool.";
        private const string Definition = "Simple M3U8 playlist.";
        public static bool[] CreateSimpleM3U()
        {
            var completed = new bool[4];
            var manifest = ManifestUtils.LoadManifestFromFile();
            if (manifest.Count < 1) return completed;

            WriteM3UtoFile(
                new List<string>(SortOnMostLiked(manifest)), 
                Path.Combine(FilesystemUtils.Directory.FullName, "Most Liked (SC Downloader).m3u8"), 
                out completed[0]
                );
              
            WriteM3UtoFile(
                new List<string>(SortOnMostPlayed(manifest)), 
                Path.Combine(FilesystemUtils.Directory.FullName, "Most Played (SC Downloader).m3u8"), 
                out completed[1]
                );

            WriteM3UtoFile(
                new List<string>(RecentlyChanged(manifest)), 
                Path.Combine(FilesystemUtils.Directory.FullName, "Recently Changed (SC Downloader).m3u8"), 
                out completed[2]
                );

            WriteM3UtoFile(
                new List<string>(RecentlyAdded(manifest)),
                Path.Combine(FilesystemUtils.Directory.FullName, "Recently Downloaded (SC Downloader).m3u8"),
                out completed[3]
                );

            return completed;
        }       
        public static void WriteM3UtoFile(IList<string> newM3U, string m3uPath, out bool updateSuccesful)
        {
            updateSuccesful = false;
            for (var attempts = 0; attempts < 5; attempts++)
            {
                try
                {             
                    File.WriteAllLines(m3uPath, newM3U);
                    updateSuccesful = true;
                    break;                    
                }
                catch (Exception)
                {
                    // ignored
                }
                Thread.Sleep(50); // Pause 50ms before new attempt
            }
            if (!updateSuccesful)
            {
                throw new Exception("Unable to create m3u file.");
            }
        }
        public static IList<string> SortOnMostLiked(List<Track> manifest)
        {
            IList<string> newM3U = (
                from m in manifest
                orderby m.favoritings_count ascending
                select m.LocalPathRelative).ToList();
            newM3U.Insert(0, $"# {Definition} Sorted on most liked (on SoundCloud). {GeneratedBy}");
            return newM3U;
        }
        public static IList<string> SortOnMostPlayed(List<Track> manifest)
        {
            IList<string> newM3U = (
                from m in manifest
                orderby m.playback_count descending 
                select m.LocalPathRelative).ToList();
            newM3U.Insert(0, $"# {Definition} Sorted on most played (on SoundCloud). {GeneratedBy}");
            return newM3U;
        }
        public static IList<string> RecentlyAdded(List<Track> manifest)
        {
            IList<string> newM3U = (
                from m in manifest
                orderby m.DownloadDateTimeUtc descending
                select m.LocalPathRelative).ToList();
            newM3U.Insert(0, $"# {Definition} Sorted on recently downloaded. {GeneratedBy}");
            return newM3U;
        }
        public static IList<string> RecentlyChanged(List<Track> manifest)
        {
            IList<string> newM3U = (
                from m in manifest
                orderby m.ModifiedDateTimeUtc descending
                select m.LocalPathRelative).ToList();
            newM3U.Insert(0, $"# {Definition} Sorted on recently changed. {GeneratedBy}");
            return newM3U;          
        }
    }
}